/*
 * kabuステーションAPI
 * # 定義情報   REST APIのコード一覧、エンドポイントは下記リンク参照     - [REST APIコード一覧](../ptal/error.html)
 *
 * OpenAPI spec version: 1.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * WalletMarginSuccess
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-28T15:37:06.747432777Z[GMT]")

public class WalletMarginSuccess {
  @SerializedName("MarginAccountWallet")
  private Double marginAccountWallet = null;

  @SerializedName("DepositkeepRate")
  private Double depositkeepRate = null;

  @SerializedName("ConsignmentDepositRate")
  private Double consignmentDepositRate = null;

  @SerializedName("CashOfConsignmentDepositRate")
  private Double cashOfConsignmentDepositRate = null;

  @SerializedName("MaximumSellOpenAmountPerSymbol")
  private Double maximumSellOpenAmountPerSymbol = null;

  @SerializedName("MaximumBuyOpenAmountPerSymbol")
  private Double maximumBuyOpenAmountPerSymbol = null;

  public WalletMarginSuccess marginAccountWallet(Double marginAccountWallet) {
    this.marginAccountWallet = marginAccountWallet;
    return this;
  }

   /**
   * 信用新規可能額
   * @return marginAccountWallet
  **/
  @Schema(description = "信用新規可能額")
  public Double getMarginAccountWallet() {
    return marginAccountWallet;
  }

  public void setMarginAccountWallet(Double marginAccountWallet) {
    this.marginAccountWallet = marginAccountWallet;
  }

  public WalletMarginSuccess depositkeepRate(Double depositkeepRate) {
    this.depositkeepRate = depositkeepRate;
    return this;
  }

   /**
   * 保証金維持率&lt;br&gt;※銘柄指定の場合のみ&lt;br&gt;※銘柄が指定されなかった場合、0.0を返す。
   * @return depositkeepRate
  **/
  @Schema(description = "保証金維持率<br>※銘柄指定の場合のみ<br>※銘柄が指定されなかった場合、0.0を返す。")
  public Double getDepositkeepRate() {
    return depositkeepRate;
  }

  public void setDepositkeepRate(Double depositkeepRate) {
    this.depositkeepRate = depositkeepRate;
  }

  public WalletMarginSuccess consignmentDepositRate(Double consignmentDepositRate) {
    this.consignmentDepositRate = consignmentDepositRate;
    return this;
  }

   /**
   * 委託保証金率&lt;br&gt;※銘柄指定の場合のみ。&lt;br&gt;※銘柄が指定されなかった場合、Noneを返す。
   * @return consignmentDepositRate
  **/
  @Schema(description = "委託保証金率<br>※銘柄指定の場合のみ。<br>※銘柄が指定されなかった場合、Noneを返す。")
  public Double getConsignmentDepositRate() {
    return consignmentDepositRate;
  }

  public void setConsignmentDepositRate(Double consignmentDepositRate) {
    this.consignmentDepositRate = consignmentDepositRate;
  }

  public WalletMarginSuccess cashOfConsignmentDepositRate(Double cashOfConsignmentDepositRate) {
    this.cashOfConsignmentDepositRate = cashOfConsignmentDepositRate;
    return this;
  }

   /**
   * 現金委託保証金率&lt;br&gt;※銘柄指定の場合のみ。&lt;br&gt;※銘柄が指定されなかった場合、Noneを返す。
   * @return cashOfConsignmentDepositRate
  **/
  @Schema(description = "現金委託保証金率<br>※銘柄指定の場合のみ。<br>※銘柄が指定されなかった場合、Noneを返す。")
  public Double getCashOfConsignmentDepositRate() {
    return cashOfConsignmentDepositRate;
  }

  public void setCashOfConsignmentDepositRate(Double cashOfConsignmentDepositRate) {
    this.cashOfConsignmentDepositRate = cashOfConsignmentDepositRate;
  }

  public WalletMarginSuccess maximumSellOpenAmountPerSymbol(Double maximumSellOpenAmountPerSymbol) {
    this.maximumSellOpenAmountPerSymbol = maximumSellOpenAmountPerSymbol;
    return this;
  }

   /**
   * 銘柄あたり建玉可能額（売）&lt;br&gt;※銘柄指定の場合のみ。&lt;br&gt;※銘柄あたり建玉上限対象外の場合、nullを返す。
   * @return maximumSellOpenAmountPerSymbol
  **/
  @Schema(description = "銘柄あたり建玉可能額（売）<br>※銘柄指定の場合のみ。<br>※銘柄あたり建玉上限対象外の場合、nullを返す。")
  public Double getMaximumSellOpenAmountPerSymbol() {
    return maximumSellOpenAmountPerSymbol;
  }

  public void setMaximumSellOpenAmountPerSymbol(Double maximumSellOpenAmountPerSymbol) {
    this.maximumSellOpenAmountPerSymbol = maximumSellOpenAmountPerSymbol;
  }

  public WalletMarginSuccess maximumBuyOpenAmountPerSymbol(Double maximumBuyOpenAmountPerSymbol) {
    this.maximumBuyOpenAmountPerSymbol = maximumBuyOpenAmountPerSymbol;
    return this;
  }

   /**
   * 銘柄あたり建玉可能額（買）&lt;br&gt;※銘柄指定の場合のみ。&lt;br&gt;※銘柄あたり建玉上限対象外の場合、nullを返す。
   * @return maximumBuyOpenAmountPerSymbol
  **/
  @Schema(description = "銘柄あたり建玉可能額（買）<br>※銘柄指定の場合のみ。<br>※銘柄あたり建玉上限対象外の場合、nullを返す。")
  public Double getMaximumBuyOpenAmountPerSymbol() {
    return maximumBuyOpenAmountPerSymbol;
  }

  public void setMaximumBuyOpenAmountPerSymbol(Double maximumBuyOpenAmountPerSymbol) {
    this.maximumBuyOpenAmountPerSymbol = maximumBuyOpenAmountPerSymbol;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WalletMarginSuccess walletMarginSuccess = (WalletMarginSuccess) o;
    return Objects.equals(this.marginAccountWallet, walletMarginSuccess.marginAccountWallet) &&
        Objects.equals(this.depositkeepRate, walletMarginSuccess.depositkeepRate) &&
        Objects.equals(this.consignmentDepositRate, walletMarginSuccess.consignmentDepositRate) &&
        Objects.equals(this.cashOfConsignmentDepositRate, walletMarginSuccess.cashOfConsignmentDepositRate) &&
        Objects.equals(this.maximumSellOpenAmountPerSymbol, walletMarginSuccess.maximumSellOpenAmountPerSymbol) &&
        Objects.equals(this.maximumBuyOpenAmountPerSymbol, walletMarginSuccess.maximumBuyOpenAmountPerSymbol);
  }

  @Override
  public int hashCode() {
    return Objects.hash(marginAccountWallet, depositkeepRate, consignmentDepositRate, cashOfConsignmentDepositRate, maximumSellOpenAmountPerSymbol, maximumBuyOpenAmountPerSymbol);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WalletMarginSuccess {\n");
    
    sb.append("    marginAccountWallet: ").append(toIndentedString(marginAccountWallet)).append("\n");
    sb.append("    depositkeepRate: ").append(toIndentedString(depositkeepRate)).append("\n");
    sb.append("    consignmentDepositRate: ").append(toIndentedString(consignmentDepositRate)).append("\n");
    sb.append("    cashOfConsignmentDepositRate: ").append(toIndentedString(cashOfConsignmentDepositRate)).append("\n");
    sb.append("    maximumSellOpenAmountPerSymbol: ").append(toIndentedString(maximumSellOpenAmountPerSymbol)).append("\n");
    sb.append("    maximumBuyOpenAmountPerSymbol: ").append(toIndentedString(maximumBuyOpenAmountPerSymbol)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
